service:
  name: fitbalance-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  profile: ljapp-amplify
  stage: dev
  environment:
    ENV: ${self:custom.environment.ENV.${self:custom.stage}}

custom:
  serverless-offline:    
    port: 4000
  stage: ${opt:stage, self:provider.stage}
  environment:
    ENV:
      prod: "prod"
      dev: "dev"
      pre: "pre"

resources:
  Resources:
    DevRoutineTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dev-fitbalance-routine
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    ProdRoutineTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: prod-fitbalance-routine
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  getRoutine:
    handler: handler.fb_getRoutine
    role: arn:aws:iam::895647408601:role/fitbalance-lambda-role
    events:
      - http:
          method: get
          path: routine/{userId}
          request:
            parameters:
              paths:
                userId: true
